{!!Html::style('public/css/reset.css')!!}
{!!Html::style('public/css/bootstrap.css')!!}
{!!Html::style('public/css/font-awesome.css')!!}
{!!Html::style('public/css/owl.carousel.css')!!}
{!!Html::style('public/css/jquery.fancybox.css')!!}
{!!Html::style('public/fonts/fi/flaticon.css')!!}
{!!Html::style('public/css/flexslider.css')!!}
{!!Html::style('public/css/main.css')!!}
{!!Html::style('public/css/indent.css')!!}
{!!Html::style('public/rs-plugin/css/settings.css')!!}
{!!Html::style('public/rs-plugin/css/layers.css')!!}
{!!Html::style('public/rs-plugin/css/navigation.css')!!}
{!!Html::style('public/tuner/css/colorpicker.css')!!}
{!!Html::style('public/tuner/css/styles.css')!!}
